### ISSUE TITLE
Add integration with GitHub Actions CI/CD

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-mike-011#14]
Please configure integration with GitHub Actions CI/CD:
* [ ] Create a new branch called `feature/14-gha-ci-cd-integration` and do all the following steps within that branch.
* [ ] Add `.github/workflows/ci.yml` running `pre-commit`. Set it up to run Python 3.9 env. Ensure you install `pre-commit` before running tests:
```yaml
name: tests

on:
  push:
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch the src
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pre-commit
      run: python -m pip install --upgrade pre-commit

    - name: Run pre-commit
      run: python -m pre_commit run --all-files
```
* [ ] Add GitHub Actions CI/CD badge (`master` branch) to `README.md` with a single commit. (`[![Build Status](https://github.com/kpi-web-guild/django-girls-blog-mike-011/workflows/tests/badge.svg)](https://github.com/kpi-web-guild/django-girls-blog-mike-011/actions?query=workflow%3Atests+branch%3Amaster)`)
* [ ] Push the branch and create a Pull Request for it.
